direction: right

app: {
  client: {
    label: Client App
  }

  service: {
    label: App Service
  }

  client -> service: {
    style: {
      stroke: 'orange'
    }
  }
}

authSv: {
  label: Auth Service
  az: {
    label: Authorization Server
    style: {
      3d: true
    }
  }

  idp: {
    label: Identity Provider
    style: {
      3d: true
    }
  }

  rs: {
    label: Resource Server\nOther Service
    style: {
      3d: true
    }
  }
}

user: {
  label: User
  shape: person
  style: {
    font-color: 'white'
  }
}

id_token: {
  shape: page
}

access_token: {
  shape: page
}

user -> authSv.az -> access_token: {
  style: {
    stroke: 'white'
    font-color: 'white'
  }
}
user -> authSv.idp -> id_token: {
  style: {
    stroke: 'white'
    font-color: 'white'
  }
}

access_token -> app.client -> authSv.rs: Access resource {
  style: {
    stroke: 'red'
    font-color: 'white'
  }
}
id_token -> app.client: identity info {
  style: {
    stroke: 'white'
    font-color: 'white'
  }
}

